### ISSUE TITLE
Infer speech from audio wont complete: module 'whisper.utils' has no attribute 'write_vtt'  "

### ISSUE THREAD

**Issue by Brethitmanhart** [dmarx/video-killed-the-radio-star#101]
I really have no idea of coding so I hope I'm not being painful here - but the infer speech step won't run for me. The error is below

" AttributeError: module 'whisper.utils' has no attribute 'write_vtt'  "

Here is a paste of a bit more of the code.

Transcribing audio with whisper-large
elapsed: 24.86028742790222
Transcribing audio with whisper-tiny
elapsed: 9.15235447883606
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-1ab031e9da7a>](https://localhost:8080/#) in <module>
    215         with open(outpath,'w') as f:
    216             # to do: upstream PR to control verbosity
--> 217             whisper.utils.write_vtt(
    218                 whispers[k]["segments"], # ...really?
    219                 file=f

AttributeError: module 'whisper.utils' has no attribute 'write_vtt'

If I need to do anything else please let me know.
Thanks!!!

**Comment by tbugg** [comment]
I am getting the same error. Whisper worked fine a few days ago when I ran this. Not sure what changed.

**Comment by GaelSauzet** [comment]
Same here, was working fine before tho

**Comment by mirio1247** [comment]
I literally have the same problem

**Comment by mattpetters** [comment]
same issue here!

**Comment by mattpetters** [comment]
Oh I see, API change for `whisper.utils` happened on 1/21/23, see this commit https://github.com/openai/whisper/commit/da600abd2b296a5450770b872c3765d0a5a5c769 

I'll post the changes required in a sec when I get it working. Basically they changed to a new pattern for writing diff filetypes

**Comment by mattpetters** [comment]
Something like this:

```python
        output_format = "vtt"
        writer = whisper.utils.get_writer(output_format, outpath)
        with open(outpath,'w') as f:
            # to do: upstream PR to control verbosity
            writer(
                whispers[k]["segments"], # ...really?
                file=f
            )

```

**Comment by mattpetters** [comment]
Ok, spent a long time trying to wrangle filepaths and figure that out (new to Google Colab) but really the simplest fix is in Step 2 when you install dependencies, just install a commit from before the API change:

For instance:

```
%%capture

# @title # 🛠️ Installations
!pip install vktrs[api,hf]

# this line changes to an earlier version of Whisper
!pip install git+https://github.com/openai/whisper@12e1089462a2ea92e9ade6145e7be5b6883676ff

# these are only needed for hf
!pip install "ipywidgets>=7,<8"
!sudo apt -qq install git-lfs
!git config --global credential.helper store

!pip install panel prefetch_generator
```

**Comment by mattpetters** [comment]
Someone helped me out over at OpenAI's repo
```
pip uninstall whisper
pip install openai-whisper==20230117
```

to install the older version, or for new usage:

```
from whisper.utils import get_writer

writer = get_writer("vtt", str(transcription_root))
writer(whispers[k], f"{audio_fpath}.{k}")

```

Source:
https://github.com/openai/whisper/discussions/880#discussioncomment-4761006

**Comment by Meysmerized** [comment]
OH!!! Thank you so much @mattpetters !!
I'm new to this whole thing so it took me a bit of trial and error to understand what to do 
but it ended up working when I went here



![image](https://user-images.githubusercontent.com/123426869/214200425-d85b189b-acd3-4beb-972b-d9d8a9eb805f.png)



And replaced this here !pip install git+https://github.com/openai/whisper
![image](https://user-images.githubusercontent.com/123426869/214200320-652d7f5c-3a63-4530-8a95-8ccebfca4ff5.png)



With this !pip install openai-whisper==20230117
![image](https://user-images.githubusercontent.com/123426869/214200236-c3cb56d0-4131-46e3-a57a-80a3ee6f1ce6.png)

Had to restart the whole session from scratch too, make the change before running anything...

Hope this helps someone!

**Comment by mattpetters** [comment]
> OH!!! Thank you so much @mattpetters !! I'm new to this whole thing so it took me a bit of trial and error to understand what to do but it ended up working when I went here
> 
> ![image](https://user-images.githubusercontent.com/123426869/214200425-d85b189b-acd3-4beb-972b-d9d8a9eb805f.png)
> 
> And replaced this here !pip install git+https://github.com/openai/whisper ![image](https://user-images.githubusercontent.com/123426869/214200320-652d7f5c-3a63-4530-8a95-8ccebfca4ff5.png)
> 
> With this !pip install openai-whisper==20230117 ![image](https://user-images.githubusercontent.com/123426869/214200236-c3cb56d0-4131-46e3-a57a-80a3ee6f1ce6.png)
> 
> Had to restart the whole session from scratch too, make the change before running anything...
> 
> Hope this helps someone!

Not a problem, happy to help! I also forked this project and may be making some QOL updates on that. Super fun stuff

**Comment by HarlanBrothers** [comment]
!pip install openai-whisper==20230117 did the trick! Thanks!!

**Comment by DrSharoo** [comment]
I'm still getting that error even after doing the "!pip install openai-whisper==20230117" what else should I do? @mattpetters ? Any recommendations? Is it just that one line of code?

**Comment by dmarx** [comment]
updated the notebook to work with the latest whisper, should be all good now! thanks for your patience folks.

**Comment by IamKaliber** [comment]
I'm getting this error on the infer speech from audio step. Anyone else getting this error? If so, how did you fix it?

![image](https://user-images.githubusercontent.com/126266312/221211249-a493b5a0-800f-450b-b3be-e921950c7385.png)
