### ISSUE TITLE
I can't seem to find any fitting solutions

### ISSUE THREAD

**Issue by scorpo813** [dmarx/video-killed-the-radio-star#108]
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py](https://localhost:8080/#) in _save(im, fp, tile, bufsize)
    495     try:
--> 496         fh = fp.fileno()
    497         fp.flush()

AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

BrokenPipeError                           Traceback (most recent call last)
5 frames
[/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py](https://localhost:8080/#) in putchunk(fp, cid, *data)
    981 
    982     fp.write(o32(len(data)) + cid)
--> 983     fp.write(data)
    984     crc = _crc32(data, _crc32(cid))
    985     fp.write(o32(crc))

BrokenPipeError: [Errno 32] Broken pipe

**Comment by dmarx** [comment]
this looks like it was actually an issue with ffmpeg compiling the video. not sure if it's still an issue, closing for now but feel free to reopen if you're still encountering problems
