### ISSUE TITLE
3. Animate: Execution error

### ISSUE THREAD

**Issue by hfllr** [dmarx/video-killed-the-radio-star#114]
In the 3rd part of the notebook I get the folloing error:

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/drive/MyDrive/AI/models/.cache/huggingface/diffusers'. Use `repo_type` argument if needed.

Anyone else got this error and could fix it, or knows how to fix it? I couldn't find anything related online yet..
Help would be much appreciated!

**Comment by babaibabai** [comment]
I got the same errors...no idea how to fix it

**Comment by hfllr** [comment]
works again now! @babaibabai
