### ISSUE TITLE
Error Message at "Generate init images"

### ISSUE THREAD

**Issue by FnStein** [dmarx/video-killed-the-radio-star#116]
Hello,

I'm trying to use this, but unfortunately I'm getting stuck at Generate Init images. The following error message appears:
---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

[<ipython-input-41-582b5d7dc094>](https://localhost:8080/#) in <module>
     39         prompt_starts = OmegaConf.to_container(prompt_starts)
     40     # update prompt_starts if any changes were made above
---> 41     if not np.all(df_pre.values == df.values):
     42         df_pre = copy.deepcopy(df)
     43         for i, rec in enumerate(prompt_starts):

NameError: name 'df' is not defined

Can you help?

**Comment by dmarx** [comment]
i think this is fixed, lemme know if it's still a problem

**Comment by dmarx** [comment]
if it's still an issue, let's move discussion here: #117
