### ISSUE TITLE
Generate init images ERROR

### ISSUE THREAD

**Issue by mylankoz** [dmarx/video-killed-the-radio-star#126]
i am trying to generate generate images. it fails in this step. it worked at first, now I can't get any further

RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error 
(look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' 
(/usr/local/lib/python3.9/dist-packages/google/protobuf/internal/__init__.py)

**Comment by dmarx** [comment]
should be fixed now, give it a shot and let me know if it works for you as well

**Comment by mylankoz** [comment]
great, it works, you are amazing, thanks for the quick reply
