### ISSUE TITLE
did have this working now i get same problem every time 

### ISSUE THREAD

**Issue by sheriffdude** [dmarx/video-killed-the-radio-star#131]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-2e7924adb5b2>](https://localhost:8080/#) in <cell line: 155>()
    216         with open(outpath,'w') as f:
    217             # to do: upstream PR to control verbosity
--> 218             writer.write_result(
    219                 whispers[k],
    220                 file=f,

TypeError: write_result() missing 1 required positional argument: 'options'

any help on this i have tried different videos with no luck .i did make 2 videos with this ..now even using the same link to a video same error

**Comment by MWMullowney** [comment]
I’m getting the same error. Looking forward to a fix! This is an amazing tool.

**Comment by cupcakev3** [comment]
maybe this is a dumb question but where do you specifically insert
        options = dict(
        highlight_words=False,
        max_line_width=None,
        max_line_count=None
        )

**Comment by cupcakev3** [comment]
writer.write_result(
            whispers[k],
            f,
            options 

still giving me an error

**Comment by MWMullowney** [comment]
It's still pretty touchy. I had to restart the runtime occasionally
throughout to get all the way through.

**Comment by MWMullowney** [comment]
This replaces the current "options" code within this section:

# 💬 Transcribe and segment speech using whisper#

Replace this with what I shared:

        options = whisper.DecodingOptions(
            language='en',
        )
