### ISSUE TITLE
more bugs

### ISSUE THREAD

**Issue by soklamon** [dmarx/video-killed-the-radio-star#23]
Ensuring each prompt has an associated image
[0.0 | 0] [8.8 | 8.749965] - 105 - Considering the listener is an active part of sonic production and in direct interaction with the sonic environment

---------------------------------------------------------------------------

_MultiThreadedRendezvous                  Traceback (most recent call last)

[<ipython-input-8-01ae6716a9d7>](https://localhost:8080/#) in <module>
     90               prompt,
     91               height=height,
---> 92               width=width,
     93               )
     94           )[0]

4 frames

[/usr/local/lib/python3.7/dist-packages/grpc/_channel.py](https://localhost:8080/#) in _next(self)
    824                     raise StopIteration()
    825                 elif self._state.code is not None:
--> 826                     raise self
    827 
    828 

_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "Your organization does not have enough balance to request this action (need $0.020571084, have $0 in active grants, $0 in balance)."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:104.18.20.212:443 {grpc_message:"Your organization does not have enough balance to request this action (need $0.020571084, have $0 in active grants, $0 in balance).", grpc_status:7, created_time:"2022-09-29T18:45:19.658809462+00:00"}"

**Comment by dmarx** [comment]
>  "Your organization does not have enough balance to request this action (need $0.020571084, have $0 in active grants, $0 in balance)."

the notebook currently relies on the dreamstudio api to generate images. I'll be adding an option to generate images without api calls, but as long as you're using the dreamstudio api you need to have credits on the api to generate images. this error says you're out of credits
