### ISSUE TITLE
Disable content filtering/option to disable censorship

### ISSUE THREAD

**Issue by Vorrto** [dmarx/video-killed-the-radio-star#26]
Hi, I noticed that since it's running from your library there is no easy way to add the necessary code to disable the content filters. This was the main reason I wanted to get away from using the API.

I'm used to adding
    pipe.safety_checker = lambda images, **kwargs: (images, False)
to most models to get around the issues but I can't find where to add this in here.

It seemingly finds a way to block a few images out of every song generated which is a fairly annoying issue. At the very least, it would be good that when it detects an "innapropriate" image that it keeps using new seeds until it gets a suitable one.

**Comment by Vorrto** [comment]
I noticed you may have run out of time last night trying to get that second option working so it looks like you're already on this, I tried to fix but my 6 months of Python experience isn't enough to be any use! Also removing the filter would be preferred over regenerating since it's wastes resources.

**Comment by dmarx** [comment]
calling this wontfix for now, will probably revisit in near future
