### ISSUE TITLE
Disable NSFW filter to prevent falsely flagged (blurred or blacked) generations

### ISSUE THREAD

**Issue by CognitiveTwo** [dmarx/video-killed-the-radio-star#84]
Very harmless prompts can mess up the video with black or blurred images. 
An option to turn this off would be great. Alternatively, allow to re-generate the "nsfw" generations more easily.

**Comment by dmarx** [comment]
immediately after generating init images, a table should appear. the right most colum of this table is labeled "keep" and defaults to true. double click on that value to change it to "false" to indicate you want an image regenerated. alternatively, delete any images you want regenerated (it's convenient to have the project folder in google drive in a separate tab) and just re-run the cell.

for a variety of reasons I'm currently disinclined to provide a nsfw toggle directly. Instead, I'm planning to give users more control over prompts. the caption + theme will be the default, and I plan to add a mechanism to give users the ability to specify scene-specific overrides so you won't get bogged down by prompts that consistently trigger the filter like this. 

I understand if this is disappointing. I hope my planned solution sounds like a reasonable way we can meet halfway.

**Comment by dmarx** [comment]
minor correction: I just moved that 'keep' field to the far left of the table to make it more visible
