### ISSUE TITLE
Allow to pickup video creation from earlier failed attempt (that did create lots of images)

### ISSUE THREAD

**Issue by CognitiveTwo** [dmarx/video-killed-the-radio-star#85]
For various reasons, the script may stop half way. Picking back up without re-generating everything is difficult.
[Deforum ](https://colab.research.google.com/drive/1hzGOClzRYA8DmJvVniDGsbSQl20iVBe8?authuser=1#scrollTo=qH74gBWDd2oq ) for example solves this by allowing to start from a timestamp, which is always encoded in the generated image's filename.

**Comment by dmarx** [comment]
have you experimented with resuming? it's actually pretty robust already. the "create new project" field is really more like setting the project name: if you set it to a name that you've already used, it'll detect that project on google drive and you should be able to pick up where you left off
