### ISSUE TITLE
Issue with compiling frames.

### ISSUE THREAD

**Issue by SonBrave** [dmarx/video-killed-the-radio-star#95]
Hello everyone,

Ran into an issue during the Compile Video phase. It's an IndexError and it looks like this:

<img width="911" alt="Screen Shot 2022-12-08 at 5 46 43 AM" src="https://user-images.githubusercontent.com/120179861/206887061-fec6dabc-5bfc-4085-990f-6e914c8ac47d.png">
<img width="903" alt="Screen Shot 2022-12-08 at 5 55 54 AM" src="https://user-images.githubusercontent.com/120179861/206887071-46326b6a-ff08-4d50-a230-308f23700041.png">
<img width="901" alt="Screen Shot 2022-12-08 at 5 55 45 AM" src="https://user-images.githubusercontent.com/120179861/206887074-eefbb750-4d03-42e3-b054-1f0fea867a35.png">

Any thoughts?

**Comment by SonBrave** [comment]
Started the process over from the beginning and got this new error:

<img width="1064" alt="Screen Shot 2022-12-17 at 3 56 19 PM" src="https://user-images.githubusercontent.com/120179861/208265752-50da4ff3-3eaa-4310-9c05-69f6ee25292d.png">

**Comment by Ruffeng** [comment]
I got the same error when compiling as well. Running on MacBook Pro M1. All the previous steps ran as green.

**Comment by dhorne312** [comment]
Same error on m1 MacBook Pro & windows pc i7

**Comment by dmarx** [comment]
is this still an issue?
